#!/usr/bin/env python3
"""Generate the WF-A bookkeeping UDTs from the helper scripts under `tools/`.

`collection_self_pairs` and `collection_relabel_map` cannot be ported as they stand, and the reason
is architectural rather than fixable by translation: their `<command>` reads
`$el.element_identifier` across a whole collection, and a job receives PATHS -- identifiers do not
reach it by any route. The refusal our converter prints says "restructure the tool to run once per
element"; this is the restructuring, and it is smaller than that.

⚠ THE UNLOCK IS AN IUC TOOL usegalaxy.org ALREADY INSTALLS.
`toolshed.g2.bx.psu.edu/repos/iuc/collection_element_identifiers` turns a list collection into a
text file of its element identifiers, one per line. Put that in front and both helpers become
ordinary file-in/file-out tools -- the identifiers arrive as DATA, which a container can read.

⛔ THE PYTHON IS NOT REWRITTEN HERE, IT IS INLINED VERBATIM from `tools/`. The classic wrappers keep
running it on a local Galaxy; if this file paraphrased the logic instead, the two copies would drift
and the UDT edition would quietly compute something else -- the failure mode this whole port is
supposed to avoid. Only the ARGUMENT SHAPE changes: `--ids` receives the file's contents rather than
a Cheetah-interpolated list.

    python3 scripts/build_inventory_udts.py           # write udt/
    python3 scripts/build_inventory_udts.py --check   # non-zero if the committed copies are stale
"""

from __future__ import annotations

import argparse
import pathlib
import sys
import textwrap

ROOT = pathlib.Path(__file__).resolve().parents[1]
UDT = ROOT / "udt"

#: Galaxy interpolates this ANYWHERE in a shell_command, heredocs included.
FORBIDDEN = "$("


def read_helper(relpath: str) -> str:
    """A helper script from tools/, refused if it carries the sequence Galaxy would interpolate."""
    body = (ROOT / relpath).read_text(encoding="utf-8").rstrip("\n")
    if FORBIDDEN in body:
        sys.exit(f"REFUSING: {relpath} contains `{FORBIDDEN}`, which Galaxy would interpolate "
                 f"inside the heredoc, corrupting the inlined script.")
    return body

HEADER = """# ⛔ GENERATED by scripts/build_inventory_udts.py -- do not hand-edit.
# The Python below is inlined VERBATIM from the wrapper's helper under tools/; edit it there and
# regenerate. Only the argument shape differs from the classic tool: the element identifiers arrive
# as a FILE (from the IUC collection_element_identifiers tool) rather than as a Cheetah-interpolated
# list, because a job container receives paths and never sees a collection's identifiers.
"""


#: UDT-only glue with NO classic counterpart, which is why it lives here rather than under tools/.
#:
#: ⛔ IT EXISTS BECAUSE A COLLECTION INPUT CARRIES NO IDENTITY. Measured on usegalaxy.org
#: (udt/collection_probe.gxtool.yml): `$(inputs.x)` renders a list of File records whose `basename`
#: is the DATASET name -- both elements of a two-element list read `chrom.sizes` -- while the
#: element identifiers appear nowhere. ORDER survives, identity does not. sourmash's matrix labels
#: ARE the strain names, so the identifiers have to arrive separately and be paired by position.
#:
#: ⚠ AND PAIRING BY POSITION IS ONLY SAFE IF IT IS CHECKED. A mismatch would relabel every row of
#: the similarity matrix silently -- the worst failure this pipeline can produce, because the output
#: still looks like a result. So the count is asserted before anything is sketched, and each
#: signature's name is written into the .sig by sourmash itself.
#: ⛔ THE ONE INLINED PROGRAM THAT HAD NO FILE, AND SO NO LINT. Every other helper in
#: this repository lives under tools/ and is read in by the generator, which means
#: `ruff check tools/` sees it; this one was a 129-line Python program held in a
#: STRING CONSTANT, where no linter, no type checker and no editor could reach it.
#: It is a file now, read the same way as the rest.
SOURMASH_GLUE = read_helper("tools/sourmash_panel/sourmash_panel.py")

#: What each tool's help says about a map/list built from the WRONG collection. These diverged
#: once `relabel_map` dropped the diagonal: the matching row count let WF-C turn on
#: `__RELABEL_FROM_FILE__`'s strict mode, so a wrong relabel map now FAILS THE STEP. Nothing
#: equivalent exists for the self-pair list -- `__FILTER_FROM_FILE__` has no strict mode -- so a
#: wrong one still removes nothing, silently. Saying so once, per tool, keeps the help honest.
MISMATCH_CAVEAT = {
    "self_pairs": "⚠ **Feed it the SAME collection the pairs are about.** Nothing downstream can "
                  "detect a mismatch: `__FILTER_FROM_FILE__` has no strict mode, so a self-pair "
                  "list built from the wrong collection removes nothing and reports success.",
    "relabel_map": "⚠ **Feed it the SAME collection the pairs are about**, though WF-C will now "
                   "catch you if you don't: the `A_A` diagonal is omitted so the row count equals "
                   "the element count, which lets `__RELABEL_FROM_FILE__` run in strict mode, and "
                   "strict mode refuses both a wrong row count and any element missing from the "
                   "map. Before that, an unmatched element silently kept its `A_B` identifier.",
}

#: (udt stem, tool id, helper path, tool name, description, output format, output label, version)
#:
#: ⛔ THE VERSION IS PER TOOL BECAUSE A CHANGED TOOL MUST NOT KEEP ITS OLD ONE. There is no update
#: API for a user-defined tool: every create registers a NEW tool, so an unchanged `version` leaves
#: two definitions that differ in behaviour sharing one id and one version string, and nothing in a
#: finished run says which of them executed. `relabel_map` is at 0.2.0 because it stopped emitting
#: the `A_A` diagonal -- the output is a different length for the same input, and WF-C now requires
#: the new shape -- so a run recorded against 0.1.0 cannot be assumed to have produced it.
TOOLS = (
    ("self_pairs", "brc-self-pairs", "tools/collection_self_pairs/self_pairs.py",
     "self-pair ids from element identifiers (BRC UDT)",
     "Emit one {id}_{id} line per identifier, to drop the self-cross diagonal in WF-C",
     "txt", "self-pair ids (X_X), one per line", "0.1.0"),
    ("relabel_map", "brc-relabel-map", "tools/collection_relabel_map/relabel_map.py",
     "relabel map from element identifiers (BRC UDT)",
     "Emit {a}_{b}<TAB>{a}.{b} per distinct ordered pair, to rename WF-C's cross-product cells",
     "tabular", "A_B -> A.B relabel map (2-column TSV)", "0.2.0"),
)


#: ⚠ Galaxy interpolates `$(...)` ANYWHERE in `shell_command`, heredocs included, so a NESTED
#: `$(...)` -- shell command substitution wrapped around a Galaxy expression -- is consumed as a
#: Galaxy expression and the command line cannot be built. scripts/build_softmask_udts.py has
#: refused this since it was written; this generator emitted it in two tools, and neither had ever
#: run. Assert on the RENDERED text, which is the only place the mistake is visible.
#: ⚠ Galaxy interpolates this two-character opener ANYWHERE in a shell_command, heredocs
#: included. scripts/build_softmask_udts.py has refused it in helper bodies since it was
#: written; this generator did not, and shipped two tools that could never build a command.


def assert_no_nested_substitution(rendered: dict[str, str]) -> None:
    """Refuse any `$(` nested inside another `$(` in a tool's shell_command.

    ⛔ WHY THIS MATTERS: Galaxy owns `$(...)` in a shell_command and interpolates it ANYWHERE,
    heredocs included, so a shell command substitution wrapped around a Galaxy expression has its
    OUTER form eaten and the job dies at command-build with an empty command line -- measured on
    both 26.1 and 25.0. The documented escape for a literal shell substitution is `\\$(...)`.

    ⚠ A REGEX CANNOT DO THIS, AND THE FIRST VERSION TRIED. `\\$\\((?:[^()]*\\$\\()` requires the two
    openers to have NO parenthesis between them, so every one of these slipped through -- each the
    exact construct the guard exists to refuse:
        $( (cat) ; cat '$(inputs.x.path)')
        $(tr -d '()' < '$(inputs.x.path)')
        $(python3 -c 'print(0)' '$(inputs.x.path)')
    Scan with a depth counter instead.

    ⚠ AND IT MUST READ shell_command ONLY. Run over the whole rendered YAML it also saw `help:`
    prose, so any two mentions of the opener with no `)` between them failed the build -- which is
    why two helper scripts carry a note telling their own authors not to write the sequence down.
    A guard that shapes the documentation away from naming the hazard is doing harm.

    ⛔ AND IT PARSES THE BLOCK BY HAND, BECAUSE THIS RUNS WHERE PyYAML DOES NOT EXIST. An earlier
    version reached for `yaml.safe_load` to pull out `shell_command`, which works locally and dies
    in CI with `ModuleNotFoundError: No module named 'yaml'`: the udt-drift job is STANDARD LIBRARY
    ONLY on purpose, so that a generated file going stale is still noticed when the generator's own
    toolchain is absent. A `shell_command: |` block is every following line that is indented or
    blank, up to the next line that is not -- which needs no parser.
    """
    for name, text in rendered.items():
        cmd, lines, taking = "", text.split("\n"), False
        for line in lines:
            if taking:
                if line.strip() and not line.startswith((" ", "\t")):
                    break
                cmd += line + "\n"
            elif line.startswith("shell_command:"):
                taking = True
        i = 0
        while (i := cmd.find("$(", i)) != -1:
            if i and cmd[i - 1] == "\\":          # the documented escape: passed to the shell
                i += 2
                continue
            depth, j = 0, i
            while j < len(cmd):
                if cmd[j] == "(":
                    depth += 1
                elif cmd[j] == ")":
                    depth -= 1
                    if depth == 0:
                        break
                j += 1
            inner = cmd[i + 2:j]
            k = inner.find("$(")
            if k != -1 and (k == 0 or inner[k - 1] != "\\"):
                line = cmd[:i].count("\n") + 1
                raise SystemExit(
                    f"REFUSING: {name} shell_command line {line} nests `$(` inside `$(`. Galaxy "
                    f"interpolates the outer one as an expression and the job fails with an empty "
                    f"command line before anything runs. Pass the PATH and let the inlined script "
                    f"read the file, or escape a literal shell substitution as \\$(...).")
            i = j + 1


def build() -> dict[str, str]:
    out: dict[str, str] = {}
    # ⛔ SOURMASH_GLUE IS INLINED INTO THE SAME HEREDOC AND WAS CHECKED BY NOTHING. The FORBIDDEN
    # test below covers helpers read from tools/; this constant is not read from tools/, so a `$(`
    # added to it would have been shipped. Same body, same hazard, same check.
    if FORBIDDEN in SOURMASH_GLUE:
        raise SystemExit(f"REFUSING: SOURMASH_GLUE contains `{FORBIDDEN}`, which Galaxy would "
                         f"interpolate inside the heredoc. Describe the sequence, do not write it.")
    out["sourmash_panel.gxtool.yml"] = sourmash_udt()
    for stem, tool_id, helper, name, description, ext, label, version in TOOLS:
        script = (ROOT / helper).read_text(encoding="utf-8").rstrip("\n")
        # ⛔ THE SAME CHECK build_softmask_udts.read_helper MAKES, AND FOR THE SAME REASON. Galaxy
        # interpolates the two-character opener ANYWHERE in a shell_command, heredocs included, so
        # a helper carrying one -- even inside a comment or an f-string -- is rewritten on its way
        # into the tool. assert_no_nested_substitution below only sees the NESTED form; a bare one
        # inlined from tools/ passes it and fails at command-build time with an empty command.
        if FORBIDDEN in script:
            raise SystemExit(
                f"REFUSING: {helper} contains `{FORBIDDEN}`, which Galaxy would interpolate inside "
                f"the heredoc, corrupting the inlined script. Describe the sequence, do not write it.")
        indented = "\n".join(f"  {ln}" if ln else "" for ln in script.splitlines())
        # The template already indents the first line, so only the continuations need it.
        caveat = textwrap.fill(MISMATCH_CAVEAT[stem], width=96, subsequent_indent="    ")
        out[f"{stem}.gxtool.yml"] = HEADER + f"""class: GalaxyUserTool
id: {tool_id}
version: "{version}"
name: {name}
description: {description}
container: quay.io/biocontainers/python:3.12
shell_command: |
  cat > {stem}.py <<'BRC_PY'
{indented}
  BRC_PY
  python3 {stem}.py --ids-file '$(inputs.identifiers.path)' --out {stem}.{ext}
inputs:
  - name: identifiers
    type: data
    format: txt
    label: element identifiers, one per line
    help: >-
      The output of the IUC "Extract element identifiers" tool run on the collection this is about.
      A job container cannot see a collection's identifiers, so they have to arrive as data.
outputs:
  - name: output
    type: data
    format: {ext}
    from_work_dir: {stem}.{ext}
    label: {label}
help:
  format: markdown
  content: |
    Same logic as the classic `{helper.split("/")[1]}` tool -- the Python is inlined from
    `{helper}` verbatim by `scripts/build_inventory_udts.py`, so the two cannot drift.

    **What changed is the input, and only because it had to.** The classic wrapper interpolates
    `$el.element_identifier` over the collection at command-build time. A user-defined tool gets one
    container and a set of PATHS; the identifiers are not available to it by any route. So the
    identifiers arrive as a file, produced by the IUC `collection_element_identifiers` tool, which
    usegalaxy.org installs.

    {caveat}
"""
    assert_no_nested_substitution(out)
    _stale = _check_orphans(out)
    if _stale:
        raise SystemExit(f"REFUSING: {len(_stale)} UDT(s) carry this generator's header but are no "
                         f"longer produced by build(): {_stale}. A renamed key leaves the old file "
                         f"behind, committed and checked by nothing. Delete it or restore its key.")
    return out



def sourmash_udt() -> str:
    """The one-job sourmash port: sketch every assembly, then compare, labelled by identifier."""
    indented = "\n".join(f"  {ln}" if ln else "" for ln in SOURMASH_GLUE.rstrip("\n").splitlines())
    # ⚠ RAW, FOR THE ONE BACKSLASH IN THE DISCOVERY PATTERN. `\\.sig` in a plain f-string is an
    # unrecognised escape: Python keeps the backslash but warns (SyntaxWarning on 3.12+), and a
    # future reader "fixing" the warning by doubling it would change the regex.
    return HEADER + rf"""class: GalaxyUserTool
id: brc-sourmash-panel
version: "0.12.0"
name: sourmash sketch + compare over a panel (BRC UDT)
description: MinHash signatures for every assembly in a collection and the similarity matrix over them
container: quay.io/biocontainers/sourmash:4.9.4--hdfd78af_0
requirements:
  # ⛔ WITHOUT THIS THE JOB GETS ONE CORE, AND THIS TOOL SKETCHES A WHOLE PANEL IN ONE JOB. Measured
  # on vgp: a UDT with no `resource` entry gets GALAXY_SLOTS=1 and GALAXY_MEMORY_MB=3788, and 219
  # assemblies sketched one at a time is where six hours went. `cores_min` defaults to 1, so a tool
  # that does not ask is not merely unoptimised -- it has declared one core.
  #
  # ⛔ `ram_min` IS IN MEBIBYTES. THIS COMMENT USED TO SAY THE OPPOSITE AND WAS RIGHT AT THE TIME;
  # total-perspective-vortex#205 merged 2026-09-12 and now divides MiB by 1024 to get TPV's GiB.
  # Before it, `ram_min: 32768` really was read as 32768 GiB, exceeded the destination's
  # `max_accepted_mem` of 120 and left the job unroutable with `state=error`, `exit_code=None` and
  # empty streams. After it, 32768 is the correct way to ask for 32 GiB.
  # See udt/slots_probe.gxtool.yml, and scripts/build_softmask_udts.py for what the flip cost.
  #
  # ⚠ 16 CORES FROM A MEASUREMENT: the same 23-assembly collection took 26 min at 1 core and 224 s
  # at 8 (~7x, all outputs correct). 16 rather than 8 because the 219-member panel is the target and
  # its two costs scale differently -- sketching is LINEAR in total sequence while each compare is
  # O(N^2) in members, so compare stops being negligible there in a way it was not at 23.
  # ⚠ 32 IS THE CEILING (`max_accepted_cores`), and a request above it is unroutable the same
  # silent way.
  #
  # ⚠ 32 GB IS FOR THE COMPARE PASSES, NOT THE SKETCHING. Sketching holds one ~7 MB sketch per
  # worker at scaled=1000 (confirmed: the signatures come out 6.6-8.4 MB); `sourmash compare` loads
  # EVERY signature -- ~197 M hashes over this panel, order 2-4 GB -- and `--processes` multiplies
  # what its workers touch. The old 3788 MB default sat inside that range.
  #
  # ⛔ 64 GiB BECAUSE THE 32 GiB MEASUREMENT WAS CENSORED, NOT BECAUSE 64 IS MEASURED. The
  # 219-assembly run reported `memory.peak` of 32.00 GiB against a 32 GiB grant -- exactly the
  # ceiling -- and a peak that lands on its own limit does not say what the job wanted, only that
  # the limit truncated the observation. The run before it peaked 27.81 GiB, so the true figure is
  # somewhere at or above 32 and unknown.
  #
  # ▶ RAISING IT IS WHAT PRODUCES THE MEASUREMENT. With room above the requirement the next run
  # reports an UNCENSORED peak, and this value can then be set from evidence. Leaving it at 32 and
  # waiting means learning the number from an OOM on a ~28-minute job over the whole panel.
  # `max_accepted_mem` is 120 GiB, so 64 is inside the destination; the cost is queue time, which
  # is cheap for a tool that runs once per panel rather than once per genome.
  #
  # ⚠ SET THIS FROM THE NEXT RUN'S `memory.peak`, and if that peak again equals the grant, raise
  # again rather than believing it.
  - type: resource
    cores_min: 16
    ram_min: 65536
shell_command: |
  cat > rendered.txt <<'BRC_RENDERED'
  $(inputs.assemblies)
  BRC_RENDERED
  cat > sourmash_panel.py <<'BRC_PY'
{indented}
  BRC_PY
  python3 sourmash_panel.py --processes "$GALAXY_SLOTS" --rendered rendered.txt --ids '$(inputs.identifiers.path)' --ksize '$(inputs.ksize)' --scaled '$(inputs.scaled)' --containment '$(inputs.containment)'
inputs:
  - name: assemblies
    type: data_collection
    collection_type: list
    # ⚠ RESTRICTED, AS THE CLASSIC AND BOTH SIBLING UDTs ARE. sourmash_sketch.xml declares
    # `format="fasta,fasta.gz"`, brc-samtools-faidx declares fasta,fasta.gz and brc-anchor-prep
    # gff3,gff3.gz; this input carried no `format:` at all, so a collection of any datatype was
    # selectable on the form and got sketched. It degrades loudly (the zero-hash guard fires)
    # rather than silently, but the port had dropped a validation for no stated reason.
    format: fasta,fasta.gz
    label: assemblies to sketch
    help: The panel. One signature per element, sketched in collection order.
  - name: identifiers
    type: data
    format: txt
    label: element identifiers of THAT collection, one per line
    help: >-
      From the IUC "Extract element identifiers" tool, run on the same collection. A job cannot read
      a collection's identifiers, and sourmash's matrix labels are the strain names, so they are
      supplied here and paired by position -- with the count asserted before anything is sketched.
  - name: ksize
    type: integer
    value: 31
    label: k-mer size
  - name: containment
    type: boolean
    value: false
    label: also emit size-robust containment matrices and their tree
    help: >-
      OFF by default. Jaccard divides by the union, so on a panel spanning 286 Mb to 2,297 Mb it
      penalises a size difference as if it were distance -- a 286 Mb assembly caps at 0.36 against
      an 800 Mb genome even as a perfect subset, and the 23-genome panel already run spans 2.08x.
      Turning this on adds FOUR outputs: containment (asymmetric), max-containment (symmetric),
      and a heatmap and DENDROGRAM built from the symmetric one -- which is the tree to read when
      members differ in size, because it never divides by the union. Left off by default because
      it changes WF-A's output set and that set is consumed downstream.
  - name: scaled
    type: integer
    value: 1000
    min: 1
    label: MinHash scaled factor (lower = finer, more hashes)
    help: >-
      ⛔ EXPOSED BECAUSE THE TOOL'S OWN ERROR MESSAGE TELLS YOU TO CHANGE IT. A sequence too small
      to contribute a hash at this resolution sketches to nothing, and its row in the similarity
      matrix is then byte-identical to a genome that shares nothing with anyone -- so the tool
      refuses rather than publish it. That refusal is fatal for the WHOLE panel (one job sketches
      every assembly), and until this input existed the remedy it names was unreachable: `--scaled`
      was an argparse default the tool form neither declared nor passed. Measured at scaled=1000,
      k=31: a 360 nt viroid gives 1 hash, a 2 kb plasmid 3, a 5 kb virus 7, a 16.6 kb mitochondrion
      14, a 200 kb genome 195. Lower this for a panel with small members; the default suits
      megabase assemblies.
outputs:
  - name: similarity
    type: data
    format: csv
    from_work_dir: similarity.csv
    label: sourmash similarity matrix (CSV, labelled by strain)
  # ⛔ EVERY TREE THIS TOOL DRAWS NOW ALSO LEAVES AS DATA. The Jaccard dendrogram was published only
  # as a PNG while the max-containment one had a Newick, so the single most useful question about
  # them -- do the two clusterings agree, and where -- could not be asked of the outputs at all. It
  # is the SAME emitter for both (see write_newick), because two trees built by two copies of the
  # logic are not comparable even when they look it.
  # ⚠ NOT `optional`, unlike the max-containment pair: similarity.csv is always written, so this
  # tree always exists. ⚠ AND THE ASYMMETRIC `containment` MATRIX DELIBERATELY GETS NO TREE --
  # containment(A,B) != containment(B,A), so any clustering of it is an artefact of row order.
  - name: similarity_newick
    type: data
    format: newick
    from_work_dir: similarity.newick
    label: sourmash similarity tree, Newick (average linkage over 1 - Jaccard; branch lengths are dissimilarity, NOT evolutionary distance)
  # ⛔ PUBLISHED BECAUSE JACCARD IS CONFOUNDED BY ASSEMBLY SIZE, and this panel spans 286 Mb to
  # 2,297 Mb. Jaccard divides by the UNION, so a 286 Mb assembly caps at 286/800 = 0.36 against an
  # 800 Mb genome even as a perfect subset, and a 2,297 Mb unpurged one caps at ~0.35 against the
  # same genome -- both tails read as distant for a reason that is not relatedness. Since
  # `similarity` is what WF-I's fold order consumes, that is a wrong ordering with every job green.
  # ⚠ ALONGSIDE, NOT INSTEAD: `similarity` stays as the classic workflow's output and as what the
  # heatmap and dendrogram are drawn from. And containment is ASYMMETRIC, so nothing is plotted
  # from it -- see the helper.
  # ⛔ `containment_matrix`, NOT `containment`, AND THE NAME IS LOAD-BEARING. This tool has an INPUT
  # named `containment` (the boolean that requests these matrices). While an OUTPUT shared that
  # exact name, Galaxy could not serialise the output's metadata: `GET /api/datasets/<id>` and the
  # history-contents endpoint both returned 500, a delete PUT returned 400, and the dataset
  # was ABSENT from the history contents listing -- while `/display` served correct data the whole
  # time. So the file was fine and only the record was broken, which is why it read as three
  # unrelated glitches.
  # ⚠ MEASURED, AND THE FIRST EXPLANATION WAS WRONG. It is not a substring collision: `heatmap` is
  # a substring of `max_containment_heatmap` and both work. It is EXACT equality between an input
  # name and an output name. Reproduced on a 3-assembly panel with 160-byte outputs, then fixed
  # twice over -- renaming the output cured it, and so did renaming the input while leaving the
  # output named `containment`. Only this one name was ever used by both.
  # ⚠ AND `containment_matrix` IS THE CLASSIC WORKFLOW'S OWN NAME for this output
  # (`sourmash_compare/containment_matrix`), so the two editions now agree instead of drifting.
  - name: containment_matrix
    type: data
    format: csv
    optional: true
    from_work_dir: containment.csv
    label: sourmash containment matrix (CSV, asymmetric, size-robust)
  # ⚠ THE SYMMETRIC ONE, AND THE ONLY SIZE-ROBUST MATRIX THAT CAN BE A TREE. Plain containment is
  # asymmetric, so clustering it yields an artefact of whichever triangle the algorithm read;
  # max(containment(A,B), containment(B,A)) is symmetric and still never divides by the union, so
  # it clusters honestly on a mixed-size panel. Its heatmap and dendrogram are published beside
  # the Jaccard pair rather than replacing them -- where the two trees disagree, the Jaccard one
  # is the one distorted by size.
  - name: max_containment
    type: data
    format: csv
    optional: true
    from_work_dir: max_containment.csv
    label: sourmash max-containment matrix (CSV, symmetric, size-robust)
  - name: max_containment_heatmap
    type: data
    format: png
    optional: true
    from_work_dir: maxc.matrix.png
    label: max-containment clustered heatmap
  # ⛔ THE TREE AS DATA, BECAUSE `sourmash plot` ONLY EMITS A PICTURE. Its CLI offers PNG or PDF and
  # nothing else, so the dendrogram it draws cannot be re-rooted, re-coloured, annotated or compared
  # outside Galaxy. This is the same clustering written as Newick, for iTOL / FigTree / ggtree / ete3.
  # ⚠ IT IS NOT THE SAME TREE AS THE PNG, and that is deliberate: `sourmash plot` uses scipy's
  # default SINGLE linkage, which chains through intermediates and ladders badly on a panel holding
  # haplotype pairs. This uses AVERAGE linkage (UPGMA), which is what a reader expects of a distance
  # dendrogram. Whichever is read, it must not be the one nobody chose.
  # ⚠ BRANCH LENGTHS ARE IN `1 - max_containment`, A DISSIMILARITY, NOT EVOLUTIONARY DISTANCE. On
  # this panel a haplotype pair sits near 0.62 while an 8x size pair reaches 0.858 -- because a
  # small genome IS largely inside a big one while neither haplotype contains the other. Read it as
  # "shares content with", never as descent.
  - name: max_containment_newick
    type: data
    format: newick
    optional: true
    from_work_dir: max_containment.newick
    label: max-containment tree, Newick (average linkage over 1 - max_containment; branch lengths are dissimilarity, NOT evolutionary distance)
  - name: max_containment_dendrogram
    type: data
    format: png
    optional: true
    from_work_dir: maxc.dendro.png
    label: max-containment dendrogram (the tree to read for a mixed-size panel)
  - name: heatmap
    type: data
    format: png
    from_work_dir: cmp.matrix.png
    label: sourmash clustered heatmap
  - name: dendrogram
    type: data
    format: png
    from_work_dir: cmp.dendro.png
    label: sourmash dendrogram
  # ⛔ THE OUTPUT THAT CLOSES WF-A's ONE PARITY GAP. The classic workflow publishes one .sig dataset
  # per strain from `sourmash_sketch` mapped over the panel; this tool does the sketch INSIDE the
  # compare job, so without discovery the signatures stay work-dir files and the port silently
  # published less than the thing it ports.
  # ⚠ THE DIRECTORY IS `signatures/`, NOT `stage/`, AND THE `\d+_` IS LOAD-BEARING. `stage/` is
  # keyed by index alone, so discovering it would key the collection `0000`..`000N` instead of by
  # strain. The helper copies to `{{index}}_{{strain}}.sig`, which discovery sorts by FILENAME (giving
  # PANEL order, matching every other WF-A output) while taking the element identifier from the
  # `designation` group (giving the strain, with the index nowhere in it). Measured on .org 26.1.
  # ⚠ EVERY FIELD IS SPELLED OUT BECAUSE `UserToolSource` DEFAULTS NONE OF THEM -- a bare
  # `{{pattern: ...}}` entry fails validation.
  - name: signatures
    type: collection
    collection_type: list
    label: per-strain sourmash signatures (.sig)
    discover_datasets:
      - discover_via: pattern
        pattern: '\d+_(?P<designation>.+)\.sig'
        directory: signatures
        # ⛔ `sourmash.sig`, NOT `json`, AND THE DIFFERENCE IS ONE-DIRECTIONAL. Galaxy's registry
        # makes SourmashSignature a SUBCLASS of Json, so a `sourmash.sig` dataset satisfies any
        # `json` input -- but `json` does NOT satisfy a `sourmash.sig` input, and there is NO
        # CONVERTER either way. IUC's sourmash_compare declares `format="sourmash.sig"`, so
        # signatures published as `json` cannot be piped into it at all; the datatype has to be
        # changed by hand. This output exists to BE reusable, so it must be the datatype the
        # reusing tools ask for. Requires Galaxy >= 25.0, where the datatype landed.
        format: sourmash.sig
        visible: false
        recurse: false
        match_relative_path: false
        assign_primary_output: false
        sort_key: filename
        sort_comp: lexical
help:
  format: markdown
  content: |
    Both halves of the classic WF-A pair -- `sourmash_sketch` mapped over the panel and
    `sourmash_compare` over the resulting signatures -- in ONE job.

    ⚠ **That is not a shortcut, it is what the platform allows.** A user-defined tool cannot read a
    collection's element identifiers: measured on usegalaxy.org, `$(inputs.x)` renders File records
    whose `basename` is the DATASET name, with the identifiers nowhere in them. sourmash's matrix
    labels are the strain names, so the identifiers must be supplied alongside and paired by
    position — and pairing by position across two workflow steps would be a silent relabelling
    hazard. Sketching and comparing in one job keeps the pairing inside a single assertion.

    ⛔ **The assertion is the point.** If the identifier count and the assembly count disagree, the
    job REFUSES rather than sketching. A mismatched pair would produce a similarity matrix that is
    fully populated, plausible, and wrong about which strain each row is.

    The signature names are written by `sourmash sketch --name`, so the labels in the CSV come from
    the sketches themselves rather than from a post-hoc rename.

    **The per-strain signatures come back as a collection.** The classic WF-A pair published one
    `.sig` dataset per strain — "BRC-reusable" — and doing the sketch inside this job made them
    work-dir files instead. They are copied to `signatures/{{index}}_{{strain}}.sig` after the compare and
    published as a discovered `list` collection, keyed by strain, so nothing about WF-A's output
    set is lost by collapsing the two steps.

    ⚠ **They are in PANEL order, like everything else WF-A publishes**, and that takes an index
    prefix to arrange. Discovery sorts on the FULL filename but names each element from the
    `designation` group, so the files are copied out as `{{index}}_{{strain}}.sig`: the index orders
    the collection, the group keys it, and the index appears nowhere in the identifiers. Without the
    prefix the only orders available are name-derived, which would leave `signatures` alphabetical
    while `sizes`, `busco_summaries`, `fasta_index`, `self_pairs` and `relabel_map` are all in panel
    order — one workflow, two orders, which is the shape of the WF-C2 mis-pairing incident.

    **Measured, not inferred** — usegalaxy.org 26.1, 2026-09-08, history
    `bbd44e69cb8906b51601636ef7c09ef9`. A three-element panel given in the order
    `cs10, PvP01, strain.2` — chosen so panel order and alphabetical order DIFFER, or the run could
    not have told the two apart — came back as:

    ```
    collection_type=list  element_count=3
      0  cs10       ext=json   38783 bytes  visible=False
      1  PvP01      ext=json   39038 bytes  visible=False
      2  strain.2   ext=json   37992 bytes  visible=False
    ```

    ⚠ THAT RUN PREDATES THE `sourmash.sig` CHANGE and the `ext=json` above is left as it was
    OBSERVED rather than edited to match the current declaration -- a measurement rewritten to
    agree with later code is no longer a measurement. What it establishes is unaffected: the
    ordering and the keying, neither of which depends on which datatype is named.

    **The datatype itself was then measured separately** -- usegalaxy.org, 2026-09-09, history
    `bbd44e69cb8906b5782410311f1ad341`, this tool at v0.2.0 over a two-element panel:

    ```
    per-strain sourmash signatures (.sig): 2 element(s)
      gA  extension='sourmash.sig'  peek='Sourmash signature file'
      gB  extension='sourmash.sig'  peek='Sourmash signature file'
    ```

    Three things at once: the server ACCEPTS `format: sourmash.sig` in a UDT `discover_datasets`
    block at registration, discovery HONOURS it, and the peek string is `SourmashSignature`'s own
    `set_peek` output, so the datasets carry that class and not merely that label.

    So: panel order, keyed by strain with the `0000_` prefix nowhere in the identifiers,
    the declared `format:` honoured, the elements hidden while the collection itself is visible
    (`visible: false` applies to the elements), and three distinct sizes rather than one file found
    three times. An earlier run without the prefix
    (`bbd44e69cb8906b54a726562e523b991`) returned the same three elements alphabetically, and is
    where the dot in `strain.2` was shown to survive the pattern intact.
"""

def _check_orphans(rendered: dict[str, str]) -> list[str]:
    """UDT files on disk that carry THIS generator's header but no longer correspond to an output.

    ⛔ RENAMING A KEY LEAVES THE OLD FILE BEHIND, CHECKED BY NOTHING. `--check` iterates what
    build() PRODUCES, so a file it no longer produces is simply never visited; and the sibling
    generator's orphan sweep exempts anything whose header names a different generator -- which is
    exactly what these carry. A committed, registerable, referenced-by-nothing UDT was invisible to
    all three checkers. Enumerate the DISK and subtract.
    """
    udt_dir = ROOT / "udt"
    stale = []
    for f in sorted(udt_dir.glob("*.gxtool.yml")):
        if f.name in rendered:
            continue
        head = f.read_text(encoding="utf-8")[:400]
        if "build_inventory_udts.py" in head:
            stale.append(f.name)
    return stale


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="compare against udt/ and exit non-zero if any committed copy is stale")
    args = ap.parse_args()

    stale = []
    for filename, body in build().items():
        path = UDT / filename
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if args.check:
            if current != body:
                stale.append(filename)
            continue
        path.write_text(body, encoding="utf-8")
        print(f"  {'unchanged' if current == body else 'wrote':>9} udt/{filename}")

    if args.check:
        for filename in stale:
            print(f"  STALE udt/{filename}")
        if stale:
            print("  Regenerate with: python3 scripts/build_inventory_udts.py")
            return 1
        print(f"  all committed inventory UDTs match their helpers ({len(build())} generated)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
